// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/load_balancer.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - LoadBalancerRoot

@interface LoadBalancerRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - ServerAddressResponse

typedef GPB_ENUM(ServerAddressResponse_FieldNumber) {
  ServerAddressResponse_FieldNumber_IpAddress = 1,
};

@interface ServerAddressResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasIpAddress;
@property(nonatomic, readwrite, copy, null_resettable) NSString *ipAddress;

@end

#pragma mark - ServerAddressRequest

typedef GPB_ENUM(ServerAddressRequest_FieldNumber) {
  ServerAddressRequest_FieldNumber_Userid = 1,
};

@interface ServerAddressRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
