// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/mashservice.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN


#pragma mark - MashserviceRoot

@interface MashserviceRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - RegisterRequest

typedef GPB_ENUM(RegisterRequest_FieldNumber) {
  RegisterRequest_FieldNumber_Handle = 1,
  RegisterRequest_FieldNumber_Email = 2,
  RegisterRequest_FieldNumber_PasswordHash = 3,
  RegisterRequest_FieldNumber_Name = 4,
  RegisterRequest_FieldNumber_RegisterAgent = 5,
  RegisterRequest_FieldNumber_ProfilePicLink = 6,
  RegisterRequest_FieldNumber_BannerPicLink = 7,
};

@interface RegisterRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy) NSString *passwordHash;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasRegisterAgent;
@property(nonatomic, readwrite) int32_t registerAgent;

@property(nonatomic, readwrite) BOOL hasProfilePicLink;
@property(nonatomic, readwrite, copy) NSString *profilePicLink;

@property(nonatomic, readwrite) BOOL hasBannerPicLink;
@property(nonatomic, readwrite, copy) NSString *bannerPicLink;

@end

#pragma mark - RegisterResponse

typedef GPB_ENUM(RegisterResponse_FieldNumber) {
  RegisterResponse_FieldNumber_Success = 1,
  RegisterResponse_FieldNumber_LoginToken = 3,
};

@interface RegisterResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@end

#pragma mark - SignInRequest

typedef GPB_ENUM(SignInRequest_FieldNumber) {
  SignInRequest_FieldNumber_Handle = 1,
  SignInRequest_FieldNumber_PasswordHash = 2,
};

@interface SignInRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy) NSString *passwordHash;

@end

#pragma mark - SignInResponse

typedef GPB_ENUM(SignInResponse_FieldNumber) {
  SignInResponse_FieldNumber_Userid = 1,
  SignInResponse_FieldNumber_Email = 2,
  SignInResponse_FieldNumber_Name = 3,
  SignInResponse_FieldNumber_RegisterAgent = 4,
  SignInResponse_FieldNumber_ProfilePicLink = 5,
  SignInResponse_FieldNumber_BannerPicLink = 6,
  SignInResponse_FieldNumber_Description_p = 7,
  SignInResponse_FieldNumber_LoginToken = 8,
  SignInResponse_FieldNumber_FollowersCount = 9,
  SignInResponse_FieldNumber_FollowingCount = 10,
  SignInResponse_FieldNumber_TrackCount = 11,
};

@interface SignInResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasRegisterAgent;
@property(nonatomic, readwrite) uint32_t registerAgent;

@property(nonatomic, readwrite) BOOL hasProfilePicLink;
@property(nonatomic, readwrite, copy) NSString *profilePicLink;

@property(nonatomic, readwrite) BOOL hasBannerPicLink;
@property(nonatomic, readwrite, copy) NSString *bannerPicLink;

@property(nonatomic, readwrite) BOOL hasDescription_p;
@property(nonatomic, readwrite, copy) NSString *description_p;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasFollowersCount;
@property(nonatomic, readwrite) uint32_t followersCount;

@property(nonatomic, readwrite) BOOL hasFollowingCount;
@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) BOOL hasTrackCount;
@property(nonatomic, readwrite) uint32_t trackCount;

@end

#pragma mark - UserGetRequest

typedef GPB_ENUM(UserGetRequest_FieldNumber) {
  UserGetRequest_FieldNumber_LoginToken = 1,
  UserGetRequest_FieldNumber_Userid = 2,
  UserGetRequest_FieldNumber_QueryHandle = 3,
  UserGetRequest_FieldNumber_QueryUserid = 4,
};

@interface UserGetRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQueryHandle;
@property(nonatomic, readwrite, copy) NSString *queryHandle;

@property(nonatomic, readwrite) BOOL hasQueryUserid;
@property(nonatomic, readwrite) uint32_t queryUserid;

@end

#pragma mark - UserGetResponse

typedef GPB_ENUM(UserGetResponse_FieldNumber) {
  UserGetResponse_FieldNumber_Email = 1,
  UserGetResponse_FieldNumber_Name = 2,
  UserGetResponse_FieldNumber_ProfilePicLink = 3,
  UserGetResponse_FieldNumber_BannerPicLink = 4,
  UserGetResponse_FieldNumber_Description_p = 5,
  UserGetResponse_FieldNumber_FollowersCount = 6,
  UserGetResponse_FieldNumber_FollowingCount = 7,
  UserGetResponse_FieldNumber_TrackCount = 8,
  UserGetResponse_FieldNumber_Follow = 9,
};

@interface UserGetResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasProfilePicLink;
@property(nonatomic, readwrite, copy) NSString *profilePicLink;

@property(nonatomic, readwrite) BOOL hasBannerPicLink;
@property(nonatomic, readwrite, copy) NSString *bannerPicLink;

@property(nonatomic, readwrite) BOOL hasDescription_p;
@property(nonatomic, readwrite, copy) NSString *description_p;

@property(nonatomic, readwrite) BOOL hasFollowersCount;
@property(nonatomic, readwrite) uint32_t followersCount;

@property(nonatomic, readwrite) BOOL hasFollowingCount;
@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) BOOL hasTrackCount;
@property(nonatomic, readwrite) uint32_t trackCount;

@property(nonatomic, readwrite) BOOL hasFollow;
@property(nonatomic, readwrite) BOOL follow;

@end

#pragma mark - RecordingInfoRequest

typedef GPB_ENUM(RecordingInfoRequest_FieldNumber) {
  RecordingInfoRequest_FieldNumber_LoginToken = 1,
  RecordingInfoRequest_FieldNumber_Userid = 2,
  RecordingInfoRequest_FieldNumber_Recid = 3,
};

@interface RecordingInfoRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@end

#pragma mark - RecordingGetResponse

typedef GPB_ENUM(RecordingGetResponse_FieldNumber) {
  RecordingGetResponse_FieldNumber_Title = 1,
  RecordingGetResponse_FieldNumber_Bpm = 2,
  RecordingGetResponse_FieldNumber_Bar = 3,
  RecordingGetResponse_FieldNumber_Key = 4,
  RecordingGetResponse_FieldNumber_InstrumentArray = 5,
  RecordingGetResponse_FieldNumber_FamilyArray = 6,
  RecordingGetResponse_FieldNumber_GenreArray = 7,
  RecordingGetResponse_FieldNumber_SubgenreArray = 8,
  RecordingGetResponse_FieldNumber_Feel = 9,
  RecordingGetResponse_FieldNumber_Solo = 10,
  RecordingGetResponse_FieldNumber_Uploaded = 11,
  RecordingGetResponse_FieldNumber_Format = 12,
  RecordingGetResponse_FieldNumber_PlayCount = 13,
  RecordingGetResponse_FieldNumber_LikeCount = 14,
};

@interface RecordingGetResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *instrumentArray;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *familyArray;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *genreArray;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *subgenreArray;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@property(nonatomic, readwrite) BOOL hasUploaded;
@property(nonatomic, readwrite, copy) NSString *uploaded;

@property(nonatomic, readwrite) BOOL hasFormat;
@property(nonatomic, readwrite, copy) NSString *format;

@property(nonatomic, readwrite) BOOL hasPlayCount;
@property(nonatomic, readwrite) uint32_t playCount;

@property(nonatomic, readwrite) BOOL hasLikeCount;
@property(nonatomic, readwrite) uint32_t likeCount;

@end

#pragma mark - FollowGetRequest

typedef GPB_ENUM(FollowGetRequest_FieldNumber) {
  FollowGetRequest_FieldNumber_LoginToken = 1,
  FollowGetRequest_FieldNumber_Userid = 2,
  FollowGetRequest_FieldNumber_QueryUserid = 3,
};

@interface FollowGetRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQueryUserid;
@property(nonatomic, readwrite) uint32_t queryUserid;

@end

#pragma mark - FollowGetResponse

typedef GPB_ENUM(FollowGetResponse_FieldNumber) {
  FollowGetResponse_FieldNumber_UserArray = 1,
};

@interface FollowGetResponse : GPBMessage

// |userArray| contains |UserPreview|
@property(nonatomic, readwrite, strong) NSMutableArray *userArray;

@end

#pragma mark - UserDeleteRequest

typedef GPB_ENUM(UserDeleteRequest_FieldNumber) {
  UserDeleteRequest_FieldNumber_LoginToken = 1,
  UserDeleteRequest_FieldNumber_Userid = 2,
  UserDeleteRequest_FieldNumber_QueryUserid = 3,
};

@interface UserDeleteRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQueryUserid;
@property(nonatomic, readwrite) uint32_t queryUserid;

@end

#pragma mark - UserPreview

typedef GPB_ENUM(UserPreview_FieldNumber) {
  UserPreview_FieldNumber_Userid = 1,
  UserPreview_FieldNumber_Handle = 2,
  UserPreview_FieldNumber_Name = 3,
  UserPreview_FieldNumber_ProfilePicLink = 4,
};

@interface UserPreview : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasProfilePicLink;
@property(nonatomic, readwrite, copy) NSString *profilePicLink;

@end

#pragma mark - UserFollowRequest

typedef GPB_ENUM(UserFollowRequest_FieldNumber) {
  UserFollowRequest_FieldNumber_LoginToken = 1,
  UserFollowRequest_FieldNumber_Userid = 2,
  UserFollowRequest_FieldNumber_QueryUserid = 3,
};

@interface UserFollowRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQueryUserid;
@property(nonatomic, readwrite) uint32_t queryUserid;

@end

#pragma mark - RecordingUploadRequest

typedef GPB_ENUM(RecordingUploadRequest_FieldNumber) {
  RecordingUploadRequest_FieldNumber_Userid = 1,
  RecordingUploadRequest_FieldNumber_LoginToken = 2,
  RecordingUploadRequest_FieldNumber_Title = 3,
  RecordingUploadRequest_FieldNumber_Bpm = 4,
  RecordingUploadRequest_FieldNumber_Bar = 5,
  RecordingUploadRequest_FieldNumber_Key = 6,
  RecordingUploadRequest_FieldNumber_InstrumentArray = 7,
  RecordingUploadRequest_FieldNumber_FamilyArray = 8,
  RecordingUploadRequest_FieldNumber_GenreArray = 9,
  RecordingUploadRequest_FieldNumber_SubgenreArray = 10,
  RecordingUploadRequest_FieldNumber_Feel = 11,
  RecordingUploadRequest_FieldNumber_Solo = 12,
  RecordingUploadRequest_FieldNumber_Format = 13,
  RecordingUploadRequest_FieldNumber_Handle = 14,
};

@interface RecordingUploadRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *instrumentArray;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *familyArray;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *genreArray;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *subgenreArray;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite, copy) NSString *solo;

@property(nonatomic, readwrite) BOOL hasFormat;
@property(nonatomic, readwrite, copy) NSString *format;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@end

#pragma mark - SuccessResponse

typedef GPB_ENUM(SuccessResponse_FieldNumber) {
  SuccessResponse_FieldNumber_Success = 1,
};

@interface SuccessResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) BOOL success;

@end

#pragma mark - RecordingSearchRequest

typedef GPB_ENUM(RecordingSearchRequest_FieldNumber) {
  RecordingSearchRequest_FieldNumber_LoginToken = 1,
  RecordingSearchRequest_FieldNumber_Userid = 2,
  RecordingSearchRequest_FieldNumber_Query = 3,
};

@interface RecordingSearchRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQuery;
@property(nonatomic, readwrite, copy) NSString *query;

@end

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
