// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/mashservice.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class FeedResponse_FollowStory;
@class FeedResponse_RecordingStory;
@class RecordingResponse;
@class UserPreview;


#pragma mark - MashserviceRoot

@interface MashserviceRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - RegisterRequest

typedef GPB_ENUM(RegisterRequest_FieldNumber) {
  RegisterRequest_FieldNumber_Handle = 1,
  RegisterRequest_FieldNumber_Email = 2,
  RegisterRequest_FieldNumber_PasswordHash = 3,
  RegisterRequest_FieldNumber_Name = 4,
  RegisterRequest_FieldNumber_RegisterAgent = 5,
};

@interface RegisterRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy) NSString *passwordHash;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasRegisterAgent;
@property(nonatomic, readwrite) int32_t registerAgent;

@end

#pragma mark - RegisterResponse

typedef GPB_ENUM(RegisterResponse_FieldNumber) {
  RegisterResponse_FieldNumber_LoginToken = 1,
  RegisterResponse_FieldNumber_Userid = 2,
};

@interface RegisterResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@end

#pragma mark - SignInRequest

typedef GPB_ENUM(SignInRequest_FieldNumber) {
  SignInRequest_FieldNumber_Handle = 1,
  SignInRequest_FieldNumber_PasswordHash = 2,
};

@interface SignInRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy) NSString *passwordHash;

@end

#pragma mark - SignInResponse

typedef GPB_ENUM(SignInResponse_FieldNumber) {
  SignInResponse_FieldNumber_Userid = 1,
  SignInResponse_FieldNumber_Email = 2,
  SignInResponse_FieldNumber_Name = 3,
  SignInResponse_FieldNumber_RegisterAgent = 4,
  SignInResponse_FieldNumber_UserDescription = 7,
  SignInResponse_FieldNumber_LoginToken = 8,
  SignInResponse_FieldNumber_FollowersCount = 9,
  SignInResponse_FieldNumber_FollowingCount = 10,
  SignInResponse_FieldNumber_TrackCount = 11,
};

@interface SignInResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasRegisterAgent;
@property(nonatomic, readwrite) uint32_t registerAgent;

@property(nonatomic, readwrite) BOOL hasUserDescription;
@property(nonatomic, readwrite, copy) NSString *userDescription;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasFollowersCount;
@property(nonatomic, readwrite) uint32_t followersCount;

@property(nonatomic, readwrite) BOOL hasFollowingCount;
@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) BOOL hasTrackCount;
@property(nonatomic, readwrite) uint32_t trackCount;

@end

#pragma mark - UserResponse

typedef GPB_ENUM(UserResponse_FieldNumber) {
  UserResponse_FieldNumber_Handle = 1,
  UserResponse_FieldNumber_Email = 2,
  UserResponse_FieldNumber_Name = 3,
  UserResponse_FieldNumber_UserDescription = 4,
  UserResponse_FieldNumber_FollowersCount = 5,
  UserResponse_FieldNumber_FollowingCount = 6,
  UserResponse_FieldNumber_TrackCount = 7,
  UserResponse_FieldNumber_Follow = 8,
};

@interface UserResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasUserDescription;
@property(nonatomic, readwrite, copy) NSString *userDescription;

@property(nonatomic, readwrite) BOOL hasFollowersCount;
@property(nonatomic, readwrite) uint32_t followersCount;

@property(nonatomic, readwrite) BOOL hasFollowingCount;
@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) BOOL hasTrackCount;
@property(nonatomic, readwrite) uint32_t trackCount;

@property(nonatomic, readwrite) BOOL hasFollow;
@property(nonatomic, readwrite) BOOL follow;

@end

#pragma mark - RecordingRequest

typedef GPB_ENUM(RecordingRequest_FieldNumber) {
  RecordingRequest_FieldNumber_LoginToken = 1,
  RecordingRequest_FieldNumber_Userid = 2,
  RecordingRequest_FieldNumber_Recid = 3,
};

@interface RecordingRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@end

#pragma mark - RecordingResponse

typedef GPB_ENUM(RecordingResponse_FieldNumber) {
  RecordingResponse_FieldNumber_Title = 1,
  RecordingResponse_FieldNumber_Bpm = 2,
  RecordingResponse_FieldNumber_Bar = 3,
  RecordingResponse_FieldNumber_Key = 4,
  RecordingResponse_FieldNumber_InstrumentArray = 5,
  RecordingResponse_FieldNumber_FamilyArray = 6,
  RecordingResponse_FieldNumber_GenreArray = 7,
  RecordingResponse_FieldNumber_SubgenreArray = 8,
  RecordingResponse_FieldNumber_Feel = 9,
  RecordingResponse_FieldNumber_Solo = 10,
  RecordingResponse_FieldNumber_Uploaded = 11,
  RecordingResponse_FieldNumber_Format = 12,
  RecordingResponse_FieldNumber_PlayCount = 13,
  RecordingResponse_FieldNumber_LikeCount = 14,
  RecordingResponse_FieldNumber_Recid = 15,
  RecordingResponse_FieldNumber_Userid = 16,
  RecordingResponse_FieldNumber_Handle = 17,
};

@interface RecordingResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *instrumentArray;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *familyArray;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *genreArray;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *subgenreArray;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@property(nonatomic, readwrite) BOOL hasUploaded;
@property(nonatomic, readwrite, copy) NSString *uploaded;

@property(nonatomic, readwrite) BOOL hasFormat;
@property(nonatomic, readwrite, copy) NSString *format;

@property(nonatomic, readwrite) BOOL hasPlayCount;
@property(nonatomic, readwrite) uint32_t playCount;

@property(nonatomic, readwrite) BOOL hasLikeCount;
@property(nonatomic, readwrite) uint32_t likeCount;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@end

#pragma mark - UserRecordingsResponse

typedef GPB_ENUM(UserRecordingsResponse_FieldNumber) {
  UserRecordingsResponse_FieldNumber_RecArray = 1,
};

@interface UserRecordingsResponse : GPBMessage

// |recArray| contains |RecordingResponse|
@property(nonatomic, readwrite, strong) NSMutableArray *recArray;

@end

#pragma mark - FollowGetResponse

typedef GPB_ENUM(FollowGetResponse_FieldNumber) {
  FollowGetResponse_FieldNumber_UserArray = 1,
};

@interface FollowGetResponse : GPBMessage

// |userArray| contains |UserPreview|
@property(nonatomic, readwrite, strong) NSMutableArray *userArray;

@end

#pragma mark - UserPreview

typedef GPB_ENUM(UserPreview_FieldNumber) {
  UserPreview_FieldNumber_Userid = 1,
  UserPreview_FieldNumber_Handle = 2,
  UserPreview_FieldNumber_Name = 3,
};

@interface UserPreview : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy) NSString *handle;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@end

#pragma mark - UserRequest

typedef GPB_ENUM(UserRequest_FieldNumber) {
  UserRequest_FieldNumber_LoginToken = 1,
  UserRequest_FieldNumber_Userid = 2,
  UserRequest_FieldNumber_QueryUserid = 3,
};

@interface UserRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQueryUserid;
@property(nonatomic, readwrite) uint32_t queryUserid;

@end

#pragma mark - RecordingUploadRequest

typedef GPB_ENUM(RecordingUploadRequest_FieldNumber) {
  RecordingUploadRequest_FieldNumber_Userid = 1,
  RecordingUploadRequest_FieldNumber_LoginToken = 2,
  RecordingUploadRequest_FieldNumber_Title = 3,
  RecordingUploadRequest_FieldNumber_Bpm = 4,
  RecordingUploadRequest_FieldNumber_Bar = 5,
  RecordingUploadRequest_FieldNumber_Key = 6,
  RecordingUploadRequest_FieldNumber_InstrumentArray = 7,
  RecordingUploadRequest_FieldNumber_FamilyArray = 8,
  RecordingUploadRequest_FieldNumber_GenreArray = 9,
  RecordingUploadRequest_FieldNumber_SubgenreArray = 10,
  RecordingUploadRequest_FieldNumber_Feel = 11,
  RecordingUploadRequest_FieldNumber_Solo = 12,
  RecordingUploadRequest_FieldNumber_Format = 13,
};

@interface RecordingUploadRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *instrumentArray;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *familyArray;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *genreArray;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *subgenreArray;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@property(nonatomic, readwrite) BOOL hasFormat;
@property(nonatomic, readwrite, copy) NSString *format;

@end

#pragma mark - RecordingUpdateRequest

typedef GPB_ENUM(RecordingUpdateRequest_FieldNumber) {
  RecordingUpdateRequest_FieldNumber_Userid = 1,
  RecordingUpdateRequest_FieldNumber_LoginToken = 2,
  RecordingUpdateRequest_FieldNumber_Recid = 3,
  RecordingUpdateRequest_FieldNumber_Title = 4,
  RecordingUpdateRequest_FieldNumber_InstrumentArray = 5,
  RecordingUpdateRequest_FieldNumber_FamilyArray = 6,
  RecordingUpdateRequest_FieldNumber_GenreArray = 7,
  RecordingUpdateRequest_FieldNumber_SubgenreArray = 8,
  RecordingUpdateRequest_FieldNumber_Feel = 9,
  RecordingUpdateRequest_FieldNumber_Solo = 10,
};

@interface RecordingUpdateRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy) NSString *title;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *instrumentArray;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *familyArray;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *genreArray;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong) NSMutableArray *subgenreArray;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@end

#pragma mark - SuccessResponse

typedef GPB_ENUM(SuccessResponse_FieldNumber) {
  SuccessResponse_FieldNumber_Success = 1,
};

@interface SuccessResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) BOOL success;

@end

#pragma mark - RecordingSearchRequest

typedef GPB_ENUM(RecordingSearchRequest_FieldNumber) {
  RecordingSearchRequest_FieldNumber_LoginToken = 1,
  RecordingSearchRequest_FieldNumber_Userid = 2,
  RecordingSearchRequest_FieldNumber_Query = 3,
};

@interface RecordingSearchRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQuery;
@property(nonatomic, readwrite, copy) NSString *query;

@end

#pragma mark - UserUpdateRequest

typedef GPB_ENUM(UserUpdateRequest_FieldNumber) {
  UserUpdateRequest_FieldNumber_Userid = 1,
  UserUpdateRequest_FieldNumber_LoginToken = 2,
  UserUpdateRequest_FieldNumber_Email = 3,
  UserUpdateRequest_FieldNumber_PasswordHash = 4,
  UserUpdateRequest_FieldNumber_Name = 5,
  UserUpdateRequest_FieldNumber_UserDescription = 6,
};

@interface UserUpdateRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy) NSString *email;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy) NSString *passwordHash;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy) NSString *name;

@property(nonatomic, readwrite) BOOL hasUserDescription;
@property(nonatomic, readwrite, copy) NSString *userDescription;

@end

#pragma mark - FeedRequest

typedef GPB_ENUM(FeedRequest_FieldNumber) {
  FeedRequest_FieldNumber_Userid = 1,
  FeedRequest_FieldNumber_LoginToken = 2,
};

@interface FeedRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy) NSString *loginToken;

@end

#pragma mark - FeedResponse

typedef GPB_ENUM(FeedResponse_FieldNumber) {
  FeedResponse_FieldNumber_StoryArray = 1,
};

@interface FeedResponse : GPBMessage

// |storyArray| contains |FeedResponse_Story|
@property(nonatomic, readwrite, strong) NSMutableArray *storyArray;

@end

#pragma mark - FeedResponse_FollowStory

typedef GPB_ENUM(FeedResponse_FollowStory_FieldNumber) {
  FeedResponse_FollowStory_FieldNumber_Followed = 1,
  FeedResponse_FollowStory_FieldNumber_Follower = 2,
  FeedResponse_FollowStory_FieldNumber_Timestamp = 3,
};

@interface FeedResponse_FollowStory : GPBMessage

@property(nonatomic, readwrite) BOOL hasFollowed;
@property(nonatomic, readwrite, strong) UserPreview *followed;

@property(nonatomic, readwrite) BOOL hasFollower;
@property(nonatomic, readwrite, strong) UserPreview *follower;

@property(nonatomic, readwrite) BOOL hasTimestamp;
@property(nonatomic, readwrite, copy) NSString *timestamp;

@end

#pragma mark - FeedResponse_RecordingStory

typedef GPB_ENUM(FeedResponse_RecordingStory_FieldNumber) {
  FeedResponse_RecordingStory_FieldNumber_Recording = 1,
};

@interface FeedResponse_RecordingStory : GPBMessage

@property(nonatomic, readwrite) BOOL hasRecording;
@property(nonatomic, readwrite, strong) RecordingResponse *recording;

@end

#pragma mark - FeedResponse_Story

typedef GPB_ENUM(FeedResponse_Story_FieldNumber) {
  FeedResponse_Story_FieldNumber_RecStory = 1,
  FeedResponse_Story_FieldNumber_FollowStory = 2,
};

typedef GPB_ENUM(FeedResponse_Story_Story_OneOfCase) {
  FeedResponse_Story_Story_OneOfCase_GPBUnsetOneOfCase = 0,
  FeedResponse_Story_Story_OneOfCase_RecStory = 1,
  FeedResponse_Story_Story_OneOfCase_FollowStory = 2,
};

@interface FeedResponse_Story : GPBMessage

@property(nonatomic, readonly) FeedResponse_Story_Story_OneOfCase storyOneOfCase;

@property(nonatomic, readwrite, strong) FeedResponse_RecordingStory *recStory;

@property(nonatomic, readwrite, strong) FeedResponse_FollowStory *followStory;

@end

void FeedResponse_Story_ClearStoryOneOfCase(FeedResponse_Story *message);

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
