// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/mashservice.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class RecordingResponse;
@class ScrollRequest;
@class UserPreview;
@class UserRequest;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - MashserviceRoot

@interface MashserviceRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - RegisterRequest

typedef GPB_ENUM(RegisterRequest_FieldNumber) {
  RegisterRequest_FieldNumber_Handle = 1,
  RegisterRequest_FieldNumber_Email = 2,
  RegisterRequest_FieldNumber_PasswordHash = 3,
  RegisterRequest_FieldNumber_Name = 4,
  RegisterRequest_FieldNumber_RegisterAgent = 5,
};

@interface RegisterRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *handle;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordHash;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) BOOL hasRegisterAgent;
@property(nonatomic, readwrite) int32_t registerAgent;

@end

#pragma mark - RegisterResponse

typedef GPB_ENUM(RegisterResponse_FieldNumber) {
  RegisterResponse_FieldNumber_LoginToken = 1,
  RegisterResponse_FieldNumber_Userid = 2,
};

@interface RegisterResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@end

#pragma mark - SignInRequest

typedef GPB_ENUM(SignInRequest_FieldNumber) {
  SignInRequest_FieldNumber_Handle = 1,
  SignInRequest_FieldNumber_Email = 2,
  SignInRequest_FieldNumber_PasswordHash = 3,
};

typedef GPB_ENUM(SignInRequest_Input_OneOfCase) {
  SignInRequest_Input_OneOfCase_GPBUnsetOneOfCase = 0,
  SignInRequest_Input_OneOfCase_Handle = 1,
  SignInRequest_Input_OneOfCase_Email = 2,
};

@interface SignInRequest : GPBMessage

@property(nonatomic, readonly) SignInRequest_Input_OneOfCase inputOneOfCase;

@property(nonatomic, readwrite, copy, null_resettable) NSString *handle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordHash;

@end

void SignInRequest_ClearInputOneOfCase(SignInRequest *message);

#pragma mark - SignInResponse

typedef GPB_ENUM(SignInResponse_FieldNumber) {
  SignInResponse_FieldNumber_Userid = 1,
  SignInResponse_FieldNumber_Email = 2,
  SignInResponse_FieldNumber_Name = 3,
  SignInResponse_FieldNumber_RegisterAgent = 4,
  SignInResponse_FieldNumber_UserDescription = 7,
  SignInResponse_FieldNumber_LoginToken = 8,
  SignInResponse_FieldNumber_FollowersCount = 9,
  SignInResponse_FieldNumber_FollowingCount = 10,
  SignInResponse_FieldNumber_TrackCount = 11,
  SignInResponse_FieldNumber_Handle = 12,
};

@interface SignInResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) BOOL hasRegisterAgent;
@property(nonatomic, readwrite) uint32_t registerAgent;

@property(nonatomic, readwrite) BOOL hasUserDescription;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userDescription;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasFollowersCount;
@property(nonatomic, readwrite) uint32_t followersCount;

@property(nonatomic, readwrite) BOOL hasFollowingCount;
@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) BOOL hasTrackCount;
@property(nonatomic, readwrite) uint32_t trackCount;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *handle;

@end

#pragma mark - UserResponse

typedef GPB_ENUM(UserResponse_FieldNumber) {
  UserResponse_FieldNumber_Handle = 1,
  UserResponse_FieldNumber_Email = 2,
  UserResponse_FieldNumber_Name = 3,
  UserResponse_FieldNumber_UserDescription = 4,
  UserResponse_FieldNumber_FollowersCount = 5,
  UserResponse_FieldNumber_FollowingCount = 6,
  UserResponse_FieldNumber_TrackCount = 7,
  UserResponse_FieldNumber_Follow = 8,
};

@interface UserResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *handle;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) BOOL hasUserDescription;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userDescription;

@property(nonatomic, readwrite) BOOL hasFollowersCount;
@property(nonatomic, readwrite) uint32_t followersCount;

@property(nonatomic, readwrite) BOOL hasFollowingCount;
@property(nonatomic, readwrite) uint32_t followingCount;

@property(nonatomic, readwrite) BOOL hasTrackCount;
@property(nonatomic, readwrite) uint32_t trackCount;

@property(nonatomic, readwrite) BOOL hasFollow;
@property(nonatomic, readwrite) BOOL follow;

@end

#pragma mark - RecordingRequest

typedef GPB_ENUM(RecordingRequest_FieldNumber) {
  RecordingRequest_FieldNumber_LoginToken = 1,
  RecordingRequest_FieldNumber_Userid = 2,
  RecordingRequest_FieldNumber_Recid = 3,
  RecordingRequest_FieldNumber_Family = 4,
};

@interface RecordingRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@property(nonatomic, readwrite) BOOL hasFamily;
@property(nonatomic, readwrite, copy, null_resettable) NSString *family;

@end

#pragma mark - RecordingResponse

typedef GPB_ENUM(RecordingResponse_FieldNumber) {
  RecordingResponse_FieldNumber_Title = 1,
  RecordingResponse_FieldNumber_Bpm = 2,
  RecordingResponse_FieldNumber_Bar = 3,
  RecordingResponse_FieldNumber_Key = 4,
  RecordingResponse_FieldNumber_InstrumentArray = 5,
  RecordingResponse_FieldNumber_FamilyArray = 6,
  RecordingResponse_FieldNumber_GenreArray = 7,
  RecordingResponse_FieldNumber_SubgenreArray = 8,
  RecordingResponse_FieldNumber_Feel = 9,
  RecordingResponse_FieldNumber_Solo = 10,
  RecordingResponse_FieldNumber_Uploaded = 11,
  RecordingResponse_FieldNumber_Format = 12,
  RecordingResponse_FieldNumber_PlayCount = 13,
  RecordingResponse_FieldNumber_LikeCount = 14,
  RecordingResponse_FieldNumber_Recid = 15,
  RecordingResponse_FieldNumber_Userid = 16,
  RecordingResponse_FieldNumber_Handle = 17,
  RecordingResponse_FieldNumber_MashCount = 18,
  RecordingResponse_FieldNumber_Liked = 19,
};

@interface RecordingResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *instrumentArray;
@property(nonatomic, readonly) NSUInteger instrumentArray_Count;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *familyArray;
@property(nonatomic, readonly) NSUInteger familyArray_Count;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *genreArray;
@property(nonatomic, readonly) NSUInteger genreArray_Count;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *subgenreArray;
@property(nonatomic, readonly) NSUInteger subgenreArray_Count;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@property(nonatomic, readwrite) BOOL hasUploaded;
@property(nonatomic, readwrite, copy, null_resettable) NSString *uploaded;

@property(nonatomic, readwrite) BOOL hasFormat;
@property(nonatomic, readwrite, copy, null_resettable) NSString *format;

@property(nonatomic, readwrite) BOOL hasPlayCount;
@property(nonatomic, readwrite) uint32_t playCount;

@property(nonatomic, readwrite) BOOL hasLikeCount;
@property(nonatomic, readwrite) uint32_t likeCount;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *handle;

@property(nonatomic, readwrite) BOOL hasMashCount;
@property(nonatomic, readwrite) uint32_t mashCount;

@property(nonatomic, readwrite) BOOL hasLiked;
@property(nonatomic, readwrite) BOOL liked;

@end

#pragma mark - UserRecordingsResponse

typedef GPB_ENUM(UserRecordingsResponse_FieldNumber) {
  UserRecordingsResponse_FieldNumber_RecArray = 1,
};

@interface UserRecordingsResponse : GPBMessage

// |recArray| contains |RecordingResponse|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *recArray;
@property(nonatomic, readonly) NSUInteger recArray_Count;

@end

#pragma mark - UserPreviews

typedef GPB_ENUM(UserPreviews_FieldNumber) {
  UserPreviews_FieldNumber_UserArray = 1,
};

@interface UserPreviews : GPBMessage

// |userArray| contains |UserPreview|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *userArray;
@property(nonatomic, readonly) NSUInteger userArray_Count;

@end

#pragma mark - UserPreview

typedef GPB_ENUM(UserPreview_FieldNumber) {
  UserPreview_FieldNumber_Userid = 1,
  UserPreview_FieldNumber_Handle = 2,
  UserPreview_FieldNumber_Name = 3,
};

@interface UserPreview : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasHandle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *handle;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@end

#pragma mark - UserRequest

typedef GPB_ENUM(UserRequest_FieldNumber) {
  UserRequest_FieldNumber_LoginToken = 1,
  UserRequest_FieldNumber_Userid = 2,
  UserRequest_FieldNumber_QueryUserid = 3,
};

@interface UserRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQueryUserid;
@property(nonatomic, readwrite) uint32_t queryUserid;

@end

#pragma mark - RecordingUploadRequest

typedef GPB_ENUM(RecordingUploadRequest_FieldNumber) {
  RecordingUploadRequest_FieldNumber_Userid = 1,
  RecordingUploadRequest_FieldNumber_LoginToken = 2,
  RecordingUploadRequest_FieldNumber_Title = 3,
  RecordingUploadRequest_FieldNumber_Bpm = 4,
  RecordingUploadRequest_FieldNumber_Bar = 5,
  RecordingUploadRequest_FieldNumber_Key = 6,
  RecordingUploadRequest_FieldNumber_InstrumentArray = 7,
  RecordingUploadRequest_FieldNumber_FamilyArray = 8,
  RecordingUploadRequest_FieldNumber_GenreArray = 9,
  RecordingUploadRequest_FieldNumber_SubgenreArray = 10,
  RecordingUploadRequest_FieldNumber_Feel = 11,
  RecordingUploadRequest_FieldNumber_Solo = 12,
  RecordingUploadRequest_FieldNumber_Format = 13,
};

@interface RecordingUploadRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *instrumentArray;
@property(nonatomic, readonly) NSUInteger instrumentArray_Count;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *familyArray;
@property(nonatomic, readonly) NSUInteger familyArray_Count;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *genreArray;
@property(nonatomic, readonly) NSUInteger genreArray_Count;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *subgenreArray;
@property(nonatomic, readonly) NSUInteger subgenreArray_Count;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@property(nonatomic, readwrite) BOOL hasFormat;
@property(nonatomic, readwrite, copy, null_resettable) NSString *format;

@end

#pragma mark - RecordingUpdateRequest

typedef GPB_ENUM(RecordingUpdateRequest_FieldNumber) {
  RecordingUpdateRequest_FieldNumber_Userid = 1,
  RecordingUpdateRequest_FieldNumber_LoginToken = 2,
  RecordingUpdateRequest_FieldNumber_Recid = 3,
  RecordingUpdateRequest_FieldNumber_Title = 4,
  RecordingUpdateRequest_FieldNumber_InstrumentArray = 5,
  RecordingUpdateRequest_FieldNumber_FamilyArray = 6,
  RecordingUpdateRequest_FieldNumber_GenreArray = 7,
  RecordingUpdateRequest_FieldNumber_SubgenreArray = 8,
  RecordingUpdateRequest_FieldNumber_Feel = 9,
  RecordingUpdateRequest_FieldNumber_Solo = 10,
};

@interface RecordingUpdateRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@property(nonatomic, readwrite) BOOL hasTitle;
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *instrumentArray;
@property(nonatomic, readonly) NSUInteger instrumentArray_Count;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *familyArray;
@property(nonatomic, readonly) NSUInteger familyArray_Count;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *genreArray;
@property(nonatomic, readonly) NSUInteger genreArray_Count;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *subgenreArray;
@property(nonatomic, readonly) NSUInteger subgenreArray_Count;

@property(nonatomic, readwrite) BOOL hasFeel;
@property(nonatomic, readwrite) uint32_t feel;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@end

#pragma mark - SuccessResponse

typedef GPB_ENUM(SuccessResponse_FieldNumber) {
  SuccessResponse_FieldNumber_Success = 1,
  SuccessResponse_FieldNumber_Recid = 2,
};

@interface SuccessResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasSuccess;
@property(nonatomic, readwrite) BOOL success;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@end

#pragma mark - RecordingSearchRequest

typedef GPB_ENUM(RecordingSearchRequest_FieldNumber) {
  RecordingSearchRequest_FieldNumber_LoginToken = 1,
  RecordingSearchRequest_FieldNumber_Userid = 2,
  RecordingSearchRequest_FieldNumber_Query = 3,
};

@interface RecordingSearchRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasQuery;
@property(nonatomic, readwrite, copy, null_resettable) NSString *query;

@end

#pragma mark - RecordingAnalyzeRequest

typedef GPB_ENUM(RecordingAnalyzeRequest_FieldNumber) {
  RecordingAnalyzeRequest_FieldNumber_LoginToken = 1,
  RecordingAnalyzeRequest_FieldNumber_Userid = 2,
  RecordingAnalyzeRequest_FieldNumber_Recid = 3,
  RecordingAnalyzeRequest_FieldNumber_Bpm = 4,
  RecordingAnalyzeRequest_FieldNumber_Bar = 5,
};

@interface RecordingAnalyzeRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasRecid;
@property(nonatomic, readwrite) uint32_t recid;

@property(nonatomic, readwrite) BOOL hasBpm;
@property(nonatomic, readwrite) uint32_t bpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@end

#pragma mark - UserSearchRequest

typedef GPB_ENUM(UserSearchRequest_FieldNumber) {
  UserSearchRequest_FieldNumber_LoginToken = 1,
  UserSearchRequest_FieldNumber_Userid = 2,
  UserSearchRequest_FieldNumber_Search = 3,
};

@interface UserSearchRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasSearch;
@property(nonatomic, readwrite, copy, null_resettable) NSString *search;

@end

#pragma mark - UserUpdateRequest

typedef GPB_ENUM(UserUpdateRequest_FieldNumber) {
  UserUpdateRequest_FieldNumber_Userid = 1,
  UserUpdateRequest_FieldNumber_LoginToken = 2,
  UserUpdateRequest_FieldNumber_Email = 3,
  UserUpdateRequest_FieldNumber_PasswordHash = 4,
  UserUpdateRequest_FieldNumber_Name = 5,
  UserUpdateRequest_FieldNumber_UserDescription = 6,
};

@interface UserUpdateRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasEmail;
@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite) BOOL hasPasswordHash;
@property(nonatomic, readwrite, copy, null_resettable) NSString *passwordHash;

@property(nonatomic, readwrite) BOOL hasName;
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) BOOL hasUserDescription;
@property(nonatomic, readwrite, copy, null_resettable) NSString *userDescription;

@end

#pragma mark - FeedResponse

typedef GPB_ENUM(FeedResponse_FieldNumber) {
  FeedResponse_FieldNumber_StoryArray = 1,
};

@interface FeedResponse : GPBMessage

//repeated FeedStory story = 1;
// |storyArray| contains |RecordingResponse|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *storyArray;
@property(nonatomic, readonly) NSUInteger storyArray_Count;

@end

#pragma mark - FeedRequest

typedef GPB_ENUM(FeedRequest_FieldNumber) {
  FeedRequest_FieldNumber_User = 1,
  FeedRequest_FieldNumber_Scroll = 2,
};

@interface FeedRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUser;
@property(nonatomic, readwrite, strong, null_resettable) UserRequest *user;

@property(nonatomic, readwrite) BOOL hasScroll;
@property(nonatomic, readwrite, strong, null_resettable) ScrollRequest *scroll;

@end

#pragma mark - ScrollRequest

typedef GPB_ENUM(ScrollRequest_FieldNumber) {
  ScrollRequest_FieldNumber_Offset = 1,
  ScrollRequest_FieldNumber_Updated = 2,
};

@interface ScrollRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasOffset;
@property(nonatomic, readwrite) uint32_t offset;

@property(nonatomic, readwrite) BOOL hasUpdated;
@property(nonatomic, readwrite, copy, null_resettable) NSString *updated;

@end

#pragma mark - FeedStory

typedef GPB_ENUM(FeedStory_FieldNumber) {
  FeedStory_FieldNumber_Recording = 1,
  FeedStory_FieldNumber_User = 2,
};

@interface FeedStory : GPBMessage

@property(nonatomic, readwrite) BOOL hasRecording;
@property(nonatomic, readwrite, strong, null_resettable) RecordingResponse *recording;

@property(nonatomic, readwrite) BOOL hasUser;
@property(nonatomic, readwrite, strong, null_resettable) UserPreview *user;

@end

#pragma mark - SearchTagRequest

typedef GPB_ENUM(SearchTagRequest_FieldNumber) {
  SearchTagRequest_FieldNumber_Userid = 1,
  SearchTagRequest_FieldNumber_LoginToken = 2,
  SearchTagRequest_FieldNumber_LBpm = 3,
  SearchTagRequest_FieldNumber_HBpm = 4,
  SearchTagRequest_FieldNumber_Bar = 5,
  SearchTagRequest_FieldNumber_Key = 6,
  SearchTagRequest_FieldNumber_InstrumentArray = 7,
  SearchTagRequest_FieldNumber_FamilyArray = 8,
  SearchTagRequest_FieldNumber_GenreArray = 9,
  SearchTagRequest_FieldNumber_SubgenreArray = 10,
  SearchTagRequest_FieldNumber_Solo = 11,
};

@interface SearchTagRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasLBpm;
@property(nonatomic, readwrite) uint32_t lBpm;

@property(nonatomic, readwrite) BOOL hasHBpm;
@property(nonatomic, readwrite) uint32_t hBpm;

@property(nonatomic, readwrite) BOOL hasBar;
@property(nonatomic, readwrite) uint32_t bar;

@property(nonatomic, readwrite) BOOL hasKey;
@property(nonatomic, readwrite, copy, null_resettable) NSString *key;

// |instrumentArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *instrumentArray;
@property(nonatomic, readonly) NSUInteger instrumentArray_Count;

// |familyArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *familyArray;
@property(nonatomic, readonly) NSUInteger familyArray_Count;

// |genreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *genreArray;
@property(nonatomic, readonly) NSUInteger genreArray_Count;

// |subgenreArray| contains |NSString|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *subgenreArray;
@property(nonatomic, readonly) NSUInteger subgenreArray_Count;

@property(nonatomic, readwrite) BOOL hasSolo;
@property(nonatomic, readwrite) BOOL solo;

@end

#pragma mark - Recordings

typedef GPB_ENUM(Recordings_FieldNumber) {
  Recordings_FieldNumber_RecordingArray = 1,
};

@interface Recordings : GPBMessage

// |recordingArray| contains |RecordingResponse|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *recordingArray;
@property(nonatomic, readonly) NSUInteger recordingArray_Count;

@end

#pragma mark - VersionResponse

typedef GPB_ENUM(VersionResponse_FieldNumber) {
  VersionResponse_FieldNumber_Outdated = 1,
};

@interface VersionResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasOutdated;
@property(nonatomic, readwrite) BOOL outdated;

@end

#pragma mark - VersionRequest

typedef GPB_ENUM(VersionRequest_FieldNumber) {
  VersionRequest_FieldNumber_Version = 1,
};

@interface VersionRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasVersion;
@property(nonatomic, readwrite, copy, null_resettable) NSString *version;

@end

#pragma mark - DeviceRequest

typedef GPB_ENUM(DeviceRequest_FieldNumber) {
  DeviceRequest_FieldNumber_Userid = 1,
  DeviceRequest_FieldNumber_LoginToken = 2,
  DeviceRequest_FieldNumber_DeviceToken = 3,
};

@interface DeviceRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hasUserid;
@property(nonatomic, readwrite) uint32_t userid;

@property(nonatomic, readwrite) BOOL hasLoginToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *loginToken;

@property(nonatomic, readwrite) BOOL hasDeviceToken;
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceToken;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
